### ISSUE TITLE
module 'hub' has no attribute 'mockingjay_local'

### ISSUE THREAD

**Issue by MiPlayer123** [s3prl/s3prl#248]
Hello. I am trying to run the Mockingjay downstream task using this command `python run_downstream.py -m train -u  mockingjay_local -k '<path to .ckpt>' -d phone_linear -n mockingjayDown`. on an HPC. I am getting the following error: 
```Traceback (most recent call last):
  File "run_downstream.py", line 225, in <module>
    main()
  File "run_downstream.py", line 220, in main
    runner = Runner(args, config)
  File "<path>/s3prl/downstream/runner.py", line 103, in __init__
    self.upstream = self._get_upstream()
  File "<path>/s3prl/downstream/runner.py", line 143, in _get_upstream
    Upstream = getattr(hub, self.args.upstream)
AttributeError: module 'hub' has no attribute 'mockingjay_local'
```

Please let me know how to resolve the issue or if I need to provide more details. Thanks!

**Comment by leo19941227** [comment]
Hi @MiPlayer123 

Hmmmm..... how about other upstream?
Can you try `-u wav2vec2` ?

**Comment by MiPlayer123** [comment]
I tried `-u wav2vec2` with no success still: `AttributeError: module 'hub' has no attribute 'wav2vec2'`

**Comment by leo19941227** [comment]
Hmmm..
This means the entire `hub` module is not installed correctly.
May I ask which command you used to install S3PRL?

**Comment by MiPlayer123** [comment]
I cloned the repo locally and uploaded the files to the HPC and installed all the dependencies. However, I did not run `pip install fairseq@git+https://github.com//pytorch/fairseq.git@f2146bdc7abf293186de9449bfa2272775e39e1d#egg=fairseq` as git was not available on the HPC. Could this be the issue?

**Comment by leo19941227** [comment]
Yes without installing fairseq you can not use wav2vec2.
However, it should not affect mockingjay.
Could you screenshot your `python3 run_downstream.py -h`?
Specifically I want to see what are the available options in `-u UPSTREAM`

**Comment by leo19941227** [comment]
I believe you follow the main README.md to install S3PRL by `pip install -e ./` right?

**Comment by MiPlayer123** [comment]
I did follow the main README, but I am not able to use `pip install -e ./` as it requires git. 

![image](https://user-images.githubusercontent.com/31391142/143783149-78ce99e5-8928-4a0a-a96f-be8bdcbbee2e.png)

I see now. There are no options in `S3PRL: []`

**Comment by MiPlayer123** [comment]
I figured out a way to get `pip install -e ./` to run, but I ran into an error while running it. `
ERROR: Could not install packages due to an OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /etc/pki/ca-trust/source/anchors/cert_Palo_Forward_Trusted_CA.crt` How would I be able to fix this issue.

**Comment by MiPlayer123** [comment]
I resolved that issue (it was network related). I am now getting this when running `pip install -e ./`: `ERROR: No matching distribution found for sacrebleu>=2.0.0kaldi_io` Do you know where the issue is comming from?

**Comment by leo19941227** [comment]
Oh did you pull the latest master?
I seems to me this error in setup.py was fixed by a recent PR, where a comma is missing between sacrebleu>=2.0.0 and kaldi_io

**Comment by MiPlayer123** [comment]
I cloned the latest at the time, which isn't the latest now. I was able to successfully run `pip install -e ./`. However, I still get the no module found error with nothing in `S3PRL: []` 
![image](https://user-images.githubusercontent.com/31391142/144714708-08edf9fa-04c0-41d7-b540-934174af4752.png)
What else could cause this issue ?

**Comment by MiPlayer123** [comment]
I decided to clone the later repo and start again, but I am running into issues again. I installed all the dependancies and when i try to run `python3 run_downstream.py -h`, I get this error:
```
[UpstreamExpert] - Using the default upstream expert config
Traceback (most recent call last):
  File "run_downstream.py", line 219, in <module>
    main()
  File "run_downstream.py", line 214, in main
    runner = Runner(args, config)
  File "<path>/s3prl/s3prl/downstream/runner.py", line 94, in __init__
    self.upstream = self._get_upstream()
  File "<path>/s3prl/s3prl/downstream/runner.py", line 153, in _get_upstream
    refresh = upstream_refresh,
  File "<path>/s3prl/s3prl/upstream/mockingjay/hubconf.py", line 29, in mockingjay_local
    return _UpstreamExpert(ckpt, model_config, *args, **kwargs)
  File "<path>/s3prl/s3prl/upstream/interfaces.py", line 30, in __call__
    instance = super().__call__(*args, **kwargs)
  File "<path>/s3prl/s3prl/upstream/mockingjay/expert.py", line 51, in __init__
    self.transformer = PretrainedTransformer(options, inp_dim=-1)
  File "<path>/s3prl/s3prl/upstream/mockingjay/builder.py", line 265, in __init__
    super(PretrainedTransformer, self).__init__(options, inp_dim, config, online_config, verbose)
  File "<path>/s3prl/s3prl/upstream/mockingjay/builder.py", line 81, in __init__
    self.extracter, self.inp_dim = get_extracter(self.config['audio'])
ValueError: too many values to unpack (expected 2)
```

**Comment by leo19941227** [comment]
Can you report the result of running

```
python3 run_downstream.py -m train -u mockingjay -d example -n test
```

and

```
python3 run_downstream.py -m train -u wav2vec2 -d example -n test
```

**Comment by leo19941227** [comment]
> I decided to clone the later repo and start again, but I am running into issues again. I installed all the dependancies and when i try to run `python3 run_downstream.py -h`, I get this error:
> 
> ```
> [UpstreamExpert] - Using the default upstream expert config
> Traceback (most recent call last):
>   File "run_downstream.py", line 219, in <module>
>     main()
>   File "run_downstream.py", line 214, in main
>     runner = Runner(args, config)
>   File "<path>/s3prl/s3prl/downstream/runner.py", line 94, in __init__
>     self.upstream = self._get_upstream()
>   File "<path>/s3prl/s3prl/downstream/runner.py", line 153, in _get_upstream
>     refresh = upstream_refresh,
>   File "<path>/s3prl/s3prl/upstream/mockingjay/hubconf.py", line 29, in mockingjay_local
>     return _UpstreamExpert(ckpt, model_config, *args, **kwargs)
>   File "<path>/s3prl/s3prl/upstream/interfaces.py", line 30, in __call__
>     instance = super().__call__(*args, **kwargs)
>   File "<path>/s3prl/s3prl/upstream/mockingjay/expert.py", line 51, in __init__
>     self.transformer = PretrainedTransformer(options, inp_dim=-1)
>   File "<path>/s3prl/s3prl/upstream/mockingjay/builder.py", line 265, in __init__
>     super(PretrainedTransformer, self).__init__(options, inp_dim, config, online_config, verbose)
>   File "<path>/s3prl/s3prl/upstream/mockingjay/builder.py", line 81, in __init__
>     self.extracter, self.inp_dim = get_extracter(self.config['audio'])
> ValueError: too many values to unpack (expected 2)
> ```

I think you will not run into `downstream/runner.py` if you are simply `python3 run_downstream.py -h`
Could you double check the command you used which lead to the above error message?

**Comment by MiPlayer123** [comment]
Not sure what happened before but both `python3 run_downstream.py -h` and `python3 run_downstream.py -h` ran without errors. Thanks!

I get that error I sent previously when I run `python3 run_downstream.py -m train -u mockingjay_local -k '<path>/s3prl/s3prl/result/pretrain/Mockingjay_trained/states-350000.ckpt' -d phone_linear -n mockingjayDown`. Is there something wrong with my command?

**Comment by leo19941227** [comment]
I don't see an obvious error with the above command.
Could you please share with me your trained checkpoint? (like launching a python server or upload to Gdrive)
Perhaps with it I am easier to identified this issue.

**Comment by leo19941227** [comment]
Thanks for sharing, I will work on this next Monday

**Comment by MiPlayer123** [comment]
I noticed that Mockingjay was updated, so I tried rerunning the downstream tasks. Unfortunately, I am still running into the same issue mentioned previously. I also tried to retrain the Mockingjay, which resulted in the same issue.

**Comment by leo19941227** [comment]
Hi,

I locate the problem. It is due to an update for the get_extracter API. I am fixing it now.
